version: '3.8'

services:
  app:
    build: .
    container_name: task-management-services
    ports:
      - "8000:8000"  
    depends_on:
      - redis  
    environment:
      - REDIS_HOST=redis  
      - REDIS_PORT=6379
    command: uvicorn src.main:app --reload --env-file .env --host 0.0.0.0 --port 8000
    volumes:
      - .:/app  

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"  
    volumes:
      - redis-data:/data  

volumes:
  redis-data:
